"""Add collumn 'read_by_recipient' to Messange table

Revision ID: 672acf35f57a
Revises: 
Create Date: 2023-04-13 15:06:41.033336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672acf35f57a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_by_recipient', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('read_by_recipient')

    # ### end Alembic commands ###
